[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 65.0.0", "versioningit >= 1,< 4", "wheel"]

[project]
authors = [
  { name = "Matthew Kuner", email = "matthewkuner@gmail.com" },
  { name = "Janosh Riebesell"},
  { name = "Jason Munro"},
  { name = "Aaron Kaplan"},
]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Development Status :: 4 - Beta",
  "Intended Audience :: Science/Research",
  "Operating System :: OS Independent",
  "Topic :: Scientific/Engineering",
  "Topic :: Scientific/Engineering :: Information Analysis",
  "Topic :: Scientific/Engineering :: Physics",
  "Topic :: Scientific/Engineering :: Chemistry",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
  "pymatgen-core>=2026.4.16",
  "numpy",
  "requests",
  "pydantic>=2.0.1",
  "pydantic-settings>=2.0.0",
]
description = "A comprehensive I/O validator for electronic structure calculations"
dynamic = ["version"]
keywords = ["io", "validation", "dft", "vasp"]
license = "BSD-3-Clause-LBNL"
name = "pymatgen-io-validation"
readme = "README.md"
requires-python = '>=3.11'

[dependency-groups]
lint = [
  "pre-commit>=2.12.1",
  "mypy",
  "ruff",
]
tests = [
  "pytest>=8.4.2",
  "pytest-cov>=7.0.0",
  "pytest-xdist>=3.8.0",
  "types-requests",
]

[tool.setuptools.dynamic]
readme = { file = ["README.md"] }

[project.urls]
repository = "https://github.com/materialsproject/pymatgen-io-validation"

[tool.setuptools.packages.find]
exclude = ["tests","examples"]
where = ["./"]

[tool.versioningit.vcs]
default-tag = "0.0.1"
method = "git"

[tool.ruff]
line-length = 120
extend-exclude = [
  "tests",
  "pymatgen/io/validation/check_for_excess_empty_space.py",
  "pymatgen/io/validation/compare_to_MP_ehull.py",
]

[tool.ruff.lint]
exclude = [".git","__pycache__","tests"]
ignore = ["E741","W291","W293","E501","E231","E203","W605"]

[tool.ruff.lint.pydocstyle]
convention = 'google'

[tool.mypy]
explicit_package_bases = true
namespace_packages = true
ignore_missing_imports = true
no_strict_optional = true
plugins = ["pydantic.mypy"]

[tool.coverage.run]
branch = true
include = ["pymatgen/*"]
parallel = true

[tool.coverage.paths]
source = ["pymatgen/"]

[tool.coverage.report]
show_missing = true
skip_covered = true
exclude_lines = [
  "pragma: no cover",
  "def __repr__",
  "if self.debug:",
  "if settings.DEBUG",
  "raise AssertionError",
  "raise NotImplementedError",
  "if 0:",
  "if __name__ == .__main__.:",
  "@deprecated",
  "if TYPE_CHECKING:",
]
